version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always
    env_file: ./containerConfig/psql.env
    ports:
      - 5432:5432
    volumes:
      - ./containerConfig/initSql.sql:/docker-entrypoint-initdb.d/initSql.sql
      - ./data/psql:/var/lib/postgresql/data
  mongodb:
    image: mongo:latest
    restart: always
    container_name: 'mongodb'
    env_file: ./containerConfig/mongodb.env
    ports:
      - 27017:27017
    volumes:
      - ./containerConfig/initMongo.js:/docker-entrypoint-initdb.d/initMongo.js
      - ./data/mongdb:/data/db
    command: mongod --logpath=/dev/null # --quiet
